server:
  port: 8001

spring:
   profiles:
     active: ${profileActive}
   application:
     name: ccboot-biz
#   aop:
#     proxy-target-class: false
#   datasource:
#     type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#     driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
#     url: jdbc:mysql://47.99.129.104:3306/test_sharding_01?useUnicode=true&characterEncoding=UTF-8             # 数据库名称
#     username: user01
#     password: ak402507979
#     initialSize: 5
#     minIdle: 5
#     maxActive: 20
#     maxWait: 60000
#     poolPreparedStatements: true           # 打开PSCache，并且指定每个连接上PSCache的大小
#     maxPoolPreparedStatementPerConnectionSize: 20
#     filters: stat,wall,config.logback    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录


logging:
  config: classpath:config/logback/logback-spring.xml

mybatis:
  config-location: classpath:config/mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.sinosoft.ccboot.common.model.po    # 所有Entity别名类所在包
  mapper-locations: classpath:config/mybatis/mapper/**/*.xml                       # mapper映射文件


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

apollo:
  bootstrap:
    enabled: true
  meta: http://106.12.15.87:9080/
