spring:
  boot:
    admin:
      client:
        url: http://localhost:8070
        username: admin
        password: admin123
        instance:
          service-base-url: http://localhost:${server.port}
