spring:
  boot:
    admin:
      client:
        url: http://localhost:8070
        username: admin
        password: admin123
        instance:
          service-base-url: http://localhost:${server.port}

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:9301
    executor:
      app-name: ${spring.application.name}
      ip: http://127.0.0.1:8082
      port: 8034
      logpath: E:/logs/${spring.application.name}/pmp/jobhandler
      logretentiondays: 15
    accessToken: